#!/bin/bash
# Test script for sending events to Event Grid topic
# Generated by Terraform template

# Event Grid configuration
TOPIC_ENDPOINT="${topic_endpoint}"
TOPIC_KEY="${topic_key}"

# Send high priority test event
curl -X POST \
  -H "aeg-sas-key: $TOPIC_KEY" \
  -H "Content-Type: application/json" \
  -d '[{
    "id": "'$(uuidgen)'",
    "source": "terraform-test",
    "specversion": "1.0",
    "type": "notification.created",
    "subject": "demo/notifications",
    "time": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
    "data": {
      "message": "Hello from Terraform-deployed Event Grid!",
      "priority": "high",
      "category": "terraform-demo",
      "userId": "terraform-user"
    }
  }]' \
  "$TOPIC_ENDPOINT/api/events"

echo "✅ Test event sent to Event Grid topic"