"""
Setup configuration for Enterprise Authentication CDK Python application

This package provides Infrastructure as Code for implementing enterprise authentication
using AWS Amplify with Amazon Cognito User Pools and external SAML/OIDC identity providers.

Author: Generated by CDK Recipe Generator v1.3
Recipe: Enterprise Authentication with Amplify
"""

from setuptools import setup, find_packages

# Read the requirements from requirements.txt
with open("requirements.txt", "r", encoding="utf-8") as f:
    requirements = [
        line.strip()
        for line in f
        if line.strip() and not line.startswith("#") and not line.startswith("-")
    ]

# Read the README file for long description
try:
    with open("README.md", "r", encoding="utf-8") as f:
        long_description = f.read()
except FileNotFoundError:
    long_description = "Enterprise Authentication with AWS Amplify and External Identity Providers - CDK Python Implementation"

setup(
    name="enterprise-authentication-cdk",
    version="1.0.0",
    description="CDK Python application for enterprise authentication with Amplify and external identity providers",
    long_description=long_description,
    long_description_content_type="text/markdown",
    
    # Author and contact information
    author="CDK Recipe Generator",
    author_email="support@example.com",
    
    # Project URLs
    project_urls={
        "Documentation": "https://docs.aws.amazon.com/cdk/",
        "Source": "https://github.com/aws/aws-cdk",
        "Bug Reports": "https://github.com/aws/aws-cdk/issues",
    },
    
    # Package configuration
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=requirements,
    
    # Package classification
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Systems Administration",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Security",
        "Typing :: Typed",
    ],
    
    # Keywords for discovery
    keywords=[
        "aws",
        "cdk",
        "cloud",
        "infrastructure",
        "authentication",
        "cognito",
        "amplify",
        "saml",
        "oidc",
        "enterprise",
        "identity",
        "federation",
        "single-sign-on",
        "sso"
    ],
    
    # Entry points for command-line tools
    entry_points={
        "console_scripts": [
            "deploy-enterprise-auth=app:main",
        ],
    },
    
    # Additional files to include in the package
    include_package_data=True,
    package_data={
        "": [
            "*.md",
            "*.txt",
            "*.json",
            "*.yaml",
            "*.yml"
        ],
    },
    
    # Development dependencies (extras)
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "black>=23.7.0",
            "flake8>=6.0.0",
            "mypy>=1.5.0",
            "isort>=5.12.0",
        ],
        "security": [
            "bandit>=1.7.5",
            "safety>=2.3.0",
        ],
        "docs": [
            "mkdocs>=1.5.0",
            "mkdocs-material>=9.1.0",
        ],
        "testing": [
            "moto>=4.2.0",
            "pytest-mock>=3.11.0",
            "coverage>=7.2.0",
        ],
    },
    
    # Zip safety
    zip_safe=False,
    
    # License information
    license="Apache License 2.0",
    
    # Platform compatibility
    platforms=["any"],
)