AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Simple Website Hosting with AWS Lightsail - Creates a WordPress instance with static IP
  and optional DNS configuration for small business websites. This template provides
  a cost-effective, managed hosting solution with predictable pricing.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Instance Configuration"
        Parameters:
          - InstanceName
          - InstanceBundleId
          - AvailabilityZone
      - Label:
          default: "Network Configuration"
        Parameters:
          - StaticIpName
          - EnableHTTPS
      - Label:
          default: "DNS Configuration (Optional)"
        Parameters:
          - DomainName
          - CreateDNSZone
      - Label:
          default: "Tagging"
        Parameters:
          - Environment
          - Project

    ParameterLabels:
      InstanceName:
        default: "WordPress Instance Name"
      InstanceBundleId:
        default: "Lightsail Bundle Size"
      AvailabilityZone:
        default: "Availability Zone"
      StaticIpName:
        default: "Static IP Address Name"
      EnableHTTPS:
        default: "Enable HTTPS Port"
      DomainName:
        default: "Custom Domain Name"
      CreateDNSZone:
        default: "Create DNS Zone"
      Environment:
        default: "Environment Type"
      Project:
        default: "Project Name"

Parameters:
  InstanceName:
    Type: String
    Description: Name for the WordPress Lightsail instance
    Default: wordpress-site
    MinLength: 2
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9\-]*$
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters and hyphens

  InstanceBundleId:
    Type: String
    Description: Lightsail bundle ID that defines instance specifications and pricing
    Default: nano_3_0
    AllowedValues:
      - nano_3_0      # $5/month - 1 vCPU, 0.5GB RAM, 20GB SSD
      - micro_3_0     # $10/month - 1 vCPU, 1GB RAM, 40GB SSD
      - small_3_0     # $20/month - 1 vCPU, 2GB RAM, 60GB SSD
      - medium_3_0    # $40/month - 2 vCPU, 4GB RAM, 80GB SSD
      - large_3_0     # $80/month - 2 vCPU, 8GB RAM, 160GB SSD
      - xlarge_3_0    # $160/month - 4 vCPU, 16GB RAM, 320GB SSD
    ConstraintDescription: Select a valid Lightsail bundle size

  AvailabilityZone:
    Type: String
    Description: Availability zone for the Lightsail instance (leave blank for automatic selection)
    Default: ""

  StaticIpName:
    Type: String
    Description: Name for the static IP address resource
    Default: wordpress-static-ip
    MinLength: 2
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][a-zA-Z0-9\-]*$
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters and hyphens

  EnableHTTPS:
    Type: String
    Description: Enable HTTPS (port 443) in addition to HTTP (port 80)
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

  DomainName:
    Type: String
    Description: Custom domain name for the website (optional, leave blank to use IP address)
    Default: ""
    AllowedPattern: ^$|^([a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$
    ConstraintDescription: Must be a valid domain name format or blank

  CreateDNSZone:
    Type: String
    Description: Create a Lightsail DNS zone for the domain (requires DomainName)
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

  Environment:
    Type: String
    Description: Environment type for resource tagging
    Default: Production
    AllowedValues:
      - Development
      - Staging
      - Production
      - Testing

  Project:
    Type: String
    Description: Project name for resource tagging and billing allocation
    Default: WebsiteHosting
    MinLength: 1
    MaxLength: 50

Conditions:
  # Condition to check if a custom domain is provided
  HasDomainName: !Not [!Equals [!Ref DomainName, ""]]
  
  # Condition to create DNS zone (requires domain name)
  ShouldCreateDNSZone: !And
    - !Condition HasDomainName
    - !Equals [!Ref CreateDNSZone, "true"]
  
  # Condition to enable HTTPS port
  EnableHTTPSPort: !Equals [!Ref EnableHTTPS, "true"]
  
  # Condition to use automatic AZ selection
  UseAutoAZ: !Equals [!Ref AvailabilityZone, ""]

Resources:
  # WordPress Lightsail Instance with pre-configured LAMP stack
  WordPressInstance:
    Type: AWS::Lightsail::Instance
    Properties:
      InstanceName: !Ref InstanceName
      AvailabilityZone: !If
        - UseAutoAZ
        - !Sub "${AWS::Region}a"
        - !Ref AvailabilityZone
      BlueprintId: wordpress  # Pre-configured WordPress with LAMP stack
      BundleId: !Ref InstanceBundleId
      Tags:
        - Key: Name
          Value: !Ref InstanceName
        - Key: Purpose
          Value: WebsiteHosting
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project
        - Key: Application
          Value: WordPress
        - Key: ManagedBy
          Value: CloudFormation
      UserData: !Base64 |
        #!/bin/bash
        # Additional initialization script for WordPress optimization
        
        # Update system packages
        sudo apt-get update -y
        
        # Configure WordPress for better security
        cd /opt/bitnami/wordpress
        
        # Set proper file permissions
        sudo chown -R bitnami:daemon /opt/bitnami/wordpress/
        sudo find /opt/bitnami/wordpress/ -type d -exec chmod 755 {} \;
        sudo find /opt/bitnami/wordpress/ -type f -exec chmod 644 {} \;
        sudo chmod 640 /opt/bitnami/wordpress/wp-config.php
        
        # Enable automatic security updates
        echo 'Unattended-Upgrade::Automatic-Reboot "false";' | sudo tee -a /etc/apt/apt.conf.d/50unattended-upgrades
        
        # Configure WordPress auto-updates
        echo "define('WP_AUTO_UPDATE_CORE', true);" | sudo tee -a /opt/bitnami/wordpress/wp-config.php
        
        # Log initialization completion
        echo "$(date): WordPress instance initialization completed" | sudo tee -a /var/log/wordpress-init.log

  # Static IP Address for consistent access
  StaticIPAddress:
    Type: AWS::Lightsail::StaticIp
    Properties:
      StaticIpName: !Ref StaticIpName
      AttachedTo: !Ref WordPressInstance

  # DNS Zone for custom domain (conditional)
  DNSZone:
    Type: AWS::Lightsail::Domain
    Condition: ShouldCreateDNSZone
    Properties:
      DomainName: !Ref DomainName
      Tags:
        - Key: Name
          Value: !Sub "${DomainName}-dns-zone"
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project
        - Key: ManagedBy
          Value: CloudFormation

  # A Record pointing to static IP (conditional)
  DNSRecordRoot:
    Type: AWS::Lightsail::DomainEntry
    Condition: ShouldCreateDNSZone
    Properties:
      DomainName: !Ref DomainName
      Name: "@"
      Type: A
      Target: !GetAtt StaticIPAddress.IpAddress
    DependsOn:
      - DNSZone
      - StaticIPAddress

  # CNAME Record for www subdomain (conditional)
  DNSRecordWWW:
    Type: AWS::Lightsail::DomainEntry
    Condition: ShouldCreateDNSZone
    Properties:
      DomainName: !Ref DomainName
      Name: www
      Type: CNAME
      Target: !Ref DomainName
    DependsOn:
      - DNSZone

Outputs:
  InstanceName:
    Description: Name of the created WordPress Lightsail instance
    Value: !Ref WordPressInstance
    Export:
      Name: !Sub "${AWS::StackName}-InstanceName"

  InstanceState:
    Description: Current state of the Lightsail instance
    Value: !GetAtt WordPressInstance.State.Name

  PublicIPAddress:
    Description: Static public IP address of the WordPress instance
    Value: !GetAtt StaticIPAddress.IpAddress
    Export:
      Name: !Sub "${AWS::StackName}-PublicIP"

  WebsiteURL:
    Description: URL to access the WordPress website
    Value: !If
      - HasDomainName
      - !Sub "http://${DomainName}"
      - !Sub "http://${StaticIPAddress.IpAddress}"

  AdminURL:
    Description: URL to access WordPress admin dashboard
    Value: !If
      - HasDomainName
      - !Sub "http://${DomainName}/wp-admin"
      - !Sub "http://${StaticIPAddress.IpAddress}/wp-admin"

  SSHConnectionCommand:
    Description: SSH command to connect to the instance
    Value: !Sub "ssh -i ~/.ssh/your-key-pair.pem bitnami@${StaticIPAddress.IpAddress}"

  WordPressCredentials:
    Description: Information about WordPress admin credentials
    Value: "Username: user | Password: Connect via SSH and run 'sudo cat /home/bitnami/bitnami_application_password'"

  BundleSpecs:
    Description: Instance bundle specifications and monthly cost
    Value: !Sub "${InstanceBundleId} - See AWS Lightsail pricing for current rates"

  DNSZoneStatus:
    Condition: ShouldCreateDNSZone
    Description: DNS zone creation status for custom domain
    Value: !Sub "DNS zone created for ${DomainName}"

  DNSNameservers:
    Condition: ShouldCreateDNSZone
    Description: Nameservers for the DNS zone (update your domain registrar)
    Value: "Check Lightsail console for nameserver details to configure at your domain registrar"

  SecurityConfiguration:
    Description: Firewall ports automatically configured
    Value: "HTTP (80), HTTPS (443), SSH (22) - managed by Lightsail"

  BackupRecommendation:
    Description: Backup recommendation for data protection
    Value: "Enable automatic snapshots in Lightsail console for data protection"

  MonitoringInfo:
    Description: Monitoring and metrics information
    Value: "Instance metrics available in Lightsail console and CloudWatch"

  CostOptimization:
    Description: Cost optimization recommendations
    Value: "Monitor usage and consider bundle resizing based on traffic patterns"

  NextSteps:
    Description: Recommended next steps after deployment
    Value: "1) Access WordPress admin to configure site 2) Set up SSL certificate 3) Configure backups 4) Install security plugins"