"""
Setup configuration for AWS CDK Python application.
ETL Pipelines with AWS Glue and Data Catalog Management

This setup.py file configures the Python package for the CDK application
that deploys a complete serverless ETL pipeline using AWS Glue services.

Recipe: etl-pipelines-aws-glue-data-catalog-management
Generated by CDK Generator v1.3
"""

import os
from setuptools import setup, find_packages


def read_requirements():
    """Read requirements from requirements.txt file."""
    with open("requirements.txt", "r", encoding="utf-8") as req_file:
        requirements = []
        for line in req_file:
            line = line.strip()
            if line and not line.startswith("#"):
                requirements.append(line)
        return requirements


def read_long_description():
    """Read long description from README file if it exists."""
    readme_path = "README.md"
    if os.path.exists(readme_path):
        with open(readme_path, "r", encoding="utf-8") as readme_file:
            return readme_file.read()
    return "AWS CDK Python application for ETL Pipelines with AWS Glue and Data Catalog Management"


setup(
    name="glue-etl-pipeline-cdk",
    version="1.0.0",
    description="AWS CDK Python application for ETL Pipelines with AWS Glue and Data Catalog Management",
    long_description=read_long_description(),
    long_description_content_type="text/markdown",
    author="CDK Generator",
    author_email="developer@example.com",
    url="https://github.com/your-org/glue-etl-pipeline-cdk",
    
    # Package configuration
    packages=find_packages(exclude=["tests*"]),
    include_package_data=True,
    zip_safe=False,
    
    # Python version requirement
    python_requires=">=3.8",
    
    # Dependencies
    install_requires=read_requirements(),
    
    # Development dependencies
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "black>=22.0.0",
            "flake8>=5.0.0",
            "mypy>=1.0.0",
            "sphinx>=5.0.0",
            "sphinx-rtd-theme>=1.0.0",
        ],
        "test": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "moto>=4.0.0",
            "boto3-stubs[essential]>=1.26.0",
        ]
    },
    
    # Entry points for command-line tools
    entry_points={
        "console_scripts": [
            "deploy-glue-pipeline=app:main",
        ],
    },
    
    # Package metadata
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Systems Administration",
        "Topic :: Utilities",
    ],
    
    # Keywords for package discovery
    keywords=[
        "aws",
        "cdk",
        "glue",
        "etl",
        "data-catalog",
        "serverless",
        "data-processing",
        "analytics",
        "infrastructure-as-code",
        "cloud-formation"
    ],
    
    # Project URLs
    project_urls={
        "Documentation": "https://docs.aws.amazon.com/cdk/",
        "Source": "https://github.com/your-org/glue-etl-pipeline-cdk",
        "Tracker": "https://github.com/your-org/glue-etl-pipeline-cdk/issues",
    },
    
    # Package data files
    package_data={
        "": ["*.json", "*.yaml", "*.yml", "*.md", "*.txt"],
    },
    
    # Data files outside of packages
    data_files=[
        (".", ["requirements.txt"]),
    ],
)